# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: hello world
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  watch:
    desc: web版の起動
    silent: true
    cmds:
      - dotnet watch run --project WebCalcCore/
